### ISSUE TITLE
composer require serpwow/google-search-results p problem

### ISSUE THREAD

**Issue by oidnus** [serpwow/google-search-results-php#1]
`Problem 1
    - Installation request for serpwow/google-search-results ^0.2.0 -> satisfiable by serpwow/google-search-results[0.2.0].
    - serpwow/google-search-results 0.2.0 requires serpwow/google-search-results ^0.1.8 -> satisfiable by serpwow/google-search-results[0.1.8] but these conflict with your requirements or minimum-stability.

`

**Comment by dgburton** [comment]
Thanks for reporting @oidnus 

This issue should be resolved in the latest update (0.2.1)
